name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_SSH_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker pull victornfb/tempo-tunes:latest
            docker rm -f tempo-tunes || true
            docker run -d -p 4000:4000 --name tempo-tunes \
            -e OPEN_WEATHER_BASE_URL=${{ secrets.OPEN_WEATHER_BASE_URL }} \
            -e OPEN_WEATHER_API_KEY=${{ secrets.OPEN_WEATHER_API_KEY }} \
            -e SPOTIFY_BASE_URL=${{ secrets.SPOTIFY_BASE_URL }} \
            -e SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} \
            -e SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} \
            -e SPOTIFY_ACCOUNTS_BASE_URL=${{ secrets.SPOTIFY_ACCOUNTS_BASE_URL }} \
            -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
            -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
            -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
            victornfb/tempo-tunes:latest
